documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"

enhancement:
  - changed-files:
      - any-glob-to-any-file:
          - ".agents/**"
          - ".github/**"
          - "images/**"
          - "web-ui/**"
