image:
  repository: ghcr.io/hambn/agentimg
  tag: latest
  pullPolicy: Always

replicaCount: 1
command: ["sleep", "infinity"]

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "2"
    memory: 4Gi
