# agentimg interactive Zsh defaults. Keep this portable across Ubuntu and Alpine.
zsh_config_dir="${ZDOTDIR:-$HOME}"
[[ -r "$zsh_config_dir/.zprofile" ]] && source "$zsh_config_dir/.zprofile"

if [[ -o interactive ]]; then
  setopt AUTO_CD AUTO_PUSHD HIST_IGNORE_ALL_DUPS HIST_REDUCE_BLANKS
  setopt INTERACTIVE_COMMENTS PROMPT_SUBST SHARE_HISTORY

  HISTFILE="${ZDOTDIR:-$HOME}/.zsh_history"
  HISTSIZE=10000
  SAVEHIST=10000
  KEYTIMEOUT=1

  fpath=(/usr/local/share/zsh/site-functions $fpath)
  autoload -Uz colors compinit
  colors
  mkdir -p "${XDG_CACHE_HOME:-$HOME/.cache}/zsh"
  compinit -d "${XDG_CACHE_HOME:-$HOME/.cache}/zsh/zcompdump"

  zstyle ':completion:*' menu select
  zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

  PROMPT='%F{242}[%F{250}%D{%H:%M:%S}%F{242}]%f %F{242}[%F{250}%1~%F{242}]%f %F{255}❯%f '

  bindkey -e
  alias ll='ls -alF'
  alias la='ls -A'
  alias g='git'
  alias gs='git status --short --branch'

  if (( $+commands[kubectl] )); then
    alias k='kubectl'
    alias kc='kubectl config current-context'
    alias kn='kubectl config set-context --current --namespace'
    compdef kubectl k
  fi

  for plugin in \
    /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh \
    /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh; do
    if [[ -r "$plugin" ]]; then
      source "$plugin"
      break
    fi
  done

  # Syntax highlighting must be loaded after widgets and other plugins.
  for plugin in \
    /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh \
    /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh; do
    if [[ -r "$plugin" ]]; then
      source "$plugin"
      break
    fi
  done
fi
